# Generated by Django 6.0.4 on 2026-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_brand_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMartDashboardBrandDF',
            fields=[
                ('brand', models.TextField(blank=True, null=True)),
                ('brand_group', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('shipping_company', models.TextField(blank=True, null=True)),
                ('delivery_option', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('cod_status', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('order_number', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('return_status', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('user_access', models.TextField(blank=True, null=True)),
                ('sku_reference_no', models.TextField(blank=True, null=True)),
                ('parent_sku_no', models.TextField(blank=True, null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('campaign_type', models.TextField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('extracted_sku', models.TextField(blank=True, null=True)),
                ('product_name_margins', models.TextField(blank=True, null=True)),
                ('product_type_alt', models.TextField(blank=True, db_column='Product_Type', null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('sub_brand', models.TextField(blank=True, null=True)),
                ('rrp', models.TextField(blank=True, null=True)),
                ('sku_match', models.TextField(blank=True, null=True)),
                ('date_update', models.TextField(blank=True, null=True)),
                ('filter_date', models.DateField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('first_transaction', models.DateTimeField(blank=True, null=True)),
                ('prev_transaction', models.DateTimeField(blank=True, null=True)),
                ('rsp', models.BigIntegerField(blank=True, null=True)),
                ('selling_price', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('is_nmv', models.BigIntegerField(blank=True, null=True)),
                ('voucher_paid_by_seller', models.BigIntegerField(blank=True, null=True)),
                ('voucher_paid', models.BigIntegerField(blank=True, null=True)),
                ('rbp', models.BigIntegerField(blank=True, null=True)),
                ('rsp_jetcom', models.BigIntegerField(blank=True, null=True)),
                ('nmv', models.BigIntegerField(blank=True, null=True)),
                ('gmv', models.BigIntegerField(blank=True, null=True)),
                ('is_new_buyer', models.IntegerField(blank=True, null=True)),
                ('is_new_buyer_in_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_mart_dashboard_brand_df',
                'managed': False,
            },
        ),
    ]
